[package]
name = "remotefs-ftp"
version = "0.5.0"
authors = ["Christian Visintin <christian.visintin1997@gmail.com>"]
categories = ["network-programming"]
documentation = "https://docs.rs/remotefs-ftp"
edition = "2024"
include = ["src/**/*", "LICENSE", "README.md", "CHANGELOG.md"]
keywords = ["remotefs", "ftp-client"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/remotefs-rs/remotefs-rs-ftp"
rust-version = "1.88.0"
description = "remotefs FTP client library"

[dependencies]
log = "0.4"
remotefs = "0.3"
rustls-pki-types = { version = "1", optional = true }
suppaftp = "11"
webpki-roots = { version = "1", optional = true }

[dev-dependencies]
env_logger = "0.11"
pretty_assertions = "1"
rand = "0.10"
testcontainers = { version = "0.28", features = ["blocking"] }

[features]
default = ["find"]
# TLS
native-tls = ["suppaftp/native-tls"]
native-tls-vendored = ["native-tls", "suppaftp/native-tls-vendored"]
rustls-aws-lc-rs = [
  "suppaftp/rustls-aws-lc-rs",
  "dep:rustls-pki-types",
  "dep:webpki-roots",
]
rustls-ring = [
  "suppaftp/rustls-ring",
  "dep:rustls-pki-types",
  "dep:webpki-roots",
]
# misc
find = ["remotefs/find"]
no-log = ["log/max_level_off"]

[target."cfg(target_os = \"windows\")"]
[target."cfg(target_os = \"windows\")".dependencies]
path-slash = "0.2"
