[package]
name = "remotefs-ftp"
version = "1.0.0"
authors = ["Christian Visintin <christian.visintin1997@gmail.com>"]
categories = ["network-programming"]
documentation = "https://docs.rs/remotefs-ftp"
edition = "2024"
include = ["src/**/*", "LICENSE", "README.md", "CHANGELOG.md"]
keywords = ["remotefs", "ftp-client"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/remotefs-rs/remotefs-rs-ftp"
rust-version = "1.89.0"
description = "remotefs FTP client library"

[package.metadata.docs.rs]
features = ["find", "rustls-aws-lc-rs", "tokio-rustls-aws-lc-rs"]
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["find"]
find = ["remotefs/find"]
native-tls = ["suppaftp/native-tls"]
native-tls-vendored = ["native-tls", "suppaftp/native-tls-vendored"]
no-log = ["log/max_level_off"]
rustls-aws-lc-rs = [
  "dep:rustls-pki-types",
  "dep:webpki-roots",
  "suppaftp/rustls-aws-lc-rs",
]
rustls-ring = [
  "dep:rustls-pki-types",
  "dep:webpki-roots",
  "suppaftp/rustls-ring",
]
tokio = ["dep:futures-io", "dep:tokio", "remotefs/tokio", "suppaftp/tokio"]
tokio-native-tls = ["suppaftp/tokio-async-native-tls", "tokio"]
tokio-native-tls-vendored = [
  "suppaftp/tokio-async-native-tls-vendored",
  "tokio-native-tls",
]
tokio-rustls-aws-lc-rs = [
  "dep:rustls-pki-types",
  "dep:webpki-roots",
  "suppaftp/tokio-rustls-aws-lc-rs",
  "tokio",
]
tokio-rustls-ring = [
  "dep:rustls-pki-types",
  "dep:webpki-roots",
  "suppaftp/tokio-rustls-ring",
  "tokio",
]

[dependencies]
futures-io = { version = "0.3", optional = true }
log = "0.4"
remotefs = "1"
rustls-pki-types = { version = "1", optional = true }
suppaftp = "12"
tokio = { version = "1", default-features = false, features = ["io-util", "net"], optional = true }
webpki-roots = { version = "1", optional = true }

[dev-dependencies]
env_logger = "0.11"
futures = "0.3"
pretty_assertions = "1"
rand = "0.10"
testcontainers = { version = "0.28", features = ["blocking"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }

[target."cfg(target_os = \"windows\")"]
[target."cfg(target_os = \"windows\")".dependencies]
path-slash = "0.2"
