name: Windows

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Build (native-tls)
        run: cargo build --features native-tls
      - name: Build (rustls)
        run: cargo build --features rustls
      - name: Build (unsecure)
        run: cargo build
      - name: Run tests
        run: cargo test --verbose --no-default-features --features find,rustls,github-actions --no-fail-fast
        env:
          RUST_LOG: trace
      - name: Format
        run: cargo fmt --all -- --check
      - name: Clippy (unsafe)
        run: cargo clippy -- -Dwarnings
      - name: Clippy (native-tls)
        run: cargo clippy --features native-tls -- -Dwarnings
      - name: Clippy (rustls)
        run: cargo clippy --features rustls -- -Dwarnings
